// Auto-generated by scripts/generate-changelog.js — do not edit manually
export interface ChangelogEntry {
  id: string;
  date: string;
  message: string;
  type: 'feature' | 'data' | 'docs' | 'fix' | 'update';
}

export const changelog: ChangelogEntry[] = [
  {
    "id": "pending",
    "date": "2026-05-11",
    "message": "תיקון שיעורי ביטוח לאומי ומס בריאות לשנת 2026 (ב״ל 1.04%+7%, בריאות 3.23%+5.17%) וכלל תקרת שכר: מי שמשכורתו החודשית עולה על 51,910 ₪ לא משלם ב״ל/בריאות על הכנסה פירותית ממניות",
    "type": "data"
  },
  {
    "id": "pending",
    "date": "2026-05-10",
    "message": "חישוב FMV ביום הענקה אוטומטי — ממוצע 20 ימי מסחר לפי שיטת JFrog (במקום הערכה לפי vest ראשון)",
    "type": "feature"
  },
  {
    "id": "b2f5a0e",
    "date": "2026-05-10",
    "message": "sale plan UI — quantity sliders, two-column layout, stable sort, full-sale surtax",
    "type": "feature"
  },
  {
    "id": "2a75704",
    "date": "2026-05-10",
    "message": "add Israeli surtax (מס יסף) and sale simulation",
    "type": "feature"
  },
  {
    "id": "8afef4b",
    "date": "2026-05-09",
    "message": "add \"מה חדש\" dropdown to header with changelog tracking",
    "type": "feature"
  },
  {
    "id": "pending",
    "date": "2026-05-09",
    "message": "הוספת חישוב מס יסף 3% + 2% (תיקון 276 / הוראת ביצוע 5/2025), סימולטור כמויות מכירה לפי lot, ושדה הכנסה הונית אחרת",
    "type": "feature"
  },
  {
    "id": "2654f6d",
    "date": "2026-05-08",
    "message": "switch to git-triggered build so serverless functions work",
    "type": "fix"
  },
  {
    "id": "0d0117d",
    "date": "2026-05-08",
    "message": "replace edge fn with Lambda serverless function for zip deploys",
    "type": "fix"
  },
  {
    "id": "40e1d93",
    "date": "2026-05-08",
    "message": "fall back to direct Yahoo Finance fetch when edge fn unavailable",
    "type": "fix"
  },
  {
    "id": "f03d99d",
    "date": "2026-05-08",
    "message": "resolve deps from public npm registry",
    "type": "fix"
  },
  {
    "id": "528584a",
    "date": "2026-05-09",
    "message": "איחוד \"זמין עכשיו\" ועדיפות מכירה לתצוגת עדיפות אחת",
    "type": "feature"
  },
  {
    "id": "67da02f",
    "date": "2026-05-08",
    "message": "סנכרון מדרגות מס הכנסה לישראל ושיפור ממשק הניתוח",
    "type": "feature"
  },
  {
    "id": "dbb4a14",
    "date": "2026-05-08",
    "message": "מחירים חיים, סקירת תיק, תיקון מס ESPP ועדיפויות מכירה ב-₪",
    "type": "feature"
  },
  {
    "id": "99b4919",
    "date": "2026-05-07",
    "message": "שחרור ראשוני של מחשבון RSU/אופציות ל-JFrog",
    "type": "feature"
  }
];
